### ISSUE TITLE
Error: Not enough disk space to create 'E:\test\temp_ex1_738842_float.bk'.

### ISSUE THREAD

**Issue by iagogv3** [talegari/bigdist#8]
Is there any workaround for this error (for example, saving just a triangular matrix)?  I do not know how many space I need for such data (738842 rows, 6 columns), but I have 308 GB free...

cc @privefl as this error comes from `bigstatsst::FBM`

Thanks!

**Comment by privefl** [comment]
I guess (738842^2 * (4 or 8) / 2^30) GB.

**Comment by iagogv3** [comment]
@privefl thanks!
